#!/bin/bash
if [[ "$#" -ne 2 ]]; then echo 'USAGE: '$(basename "$0")' <playlist-path> <cart-dir-path>'; exit 1; fi

PLAYLIST_PATH="$1"
CARTS_PATH="$2"

sanitize() {
    sed -E 's/#.*$//g' | grep -E '.' | grep -vE '^:'
}

PLAYLIST=$(curl -s https://raw.githubusercontent.com/alanxoc3/radico8/main/playlist.txt | sanitize | sort -Vu)

for cart in $(echo "$PLAYLIST" | awk -F : '{print $1}' | sort -u); do
    fullcartpath="$CARTS_PATH/$cart.p8.png"
    if [[ ! -f "$fullcartpath" ]] || [[ ! -s "$fullcartpath" ]]; then
        # found this api thanks to https://www.ebartsoft.com/pico8
        # much better & more reliable than what i was doing before to download carts
        url="http://www.lexaloffle.com/bbs/get_cart.php?cat=7&play_src=2&lid=$cart"
        echo "STARTING DOWNLOAD FOR: $url"
        wget "http://www.lexaloffle.com/bbs/get_cart.php?cat=7&play_src=2&lid=$cart" -O "$fullcartpath"
    fi
done

# Save after wget, to ensure the file actually exists.
echo Saved size: $(echo "$PLAYLIST" | tee "$PLAYLIST_PATH" | wc)
