#!/bin/bash
# must run in repo directory
TARGET_DIR=/srv/radico8

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    echo "Rerun this script as root! Exiting with non-zero error code."
    exit 1
fi

echo "Copying files..."
mkdir -p ${TARGET_DIR}/cartridges
cp cartridges/radico8.lua ${TARGET_DIR}/cartridges
cp cartridges/radico8.p8 ${TARGET_DIR}/cartridges

cp -r docker ${TARGET_DIR}/docker
cp playlist.txt start_radio start_youtube start_icecast ${TARGET_DIR}

echo "Installing systemd scripts..."

cat << EOF | tee /etc/systemd/system/radico8.service > /dev/null
[Unit]
Description=Headless pico8 instance running radico8.
After=docker.service
Requires=docker.service

[Service]
Restart=always
ExecStart=${TARGET_DIR}/start_radio /opt/pico8 ${TARGET_DIR}/cartridges ${TARGET_DIR}/playlist.txt

[Install]
WantedBy=multi-user.target
EOF

cat << EOF | tee /etc/systemd/system/radico8-youtube.service > /dev/null
[Unit]
Description=Streams radico8 to youtube.
After=radico8.service
Requires=radico8.service

[Service]
Restart=always
EnvironmentFile=/etc/radico8/youtube.env
ExecStart=${TARGET_DIR}/start_youtube

[Install]
WantedBy=multi-user.target
EOF

cat << EOF | tee /etc/systemd/system/radico8-icecast.service > /dev/null
[Unit]
Description=Streams radico8 to icecast.
After=radico8.service
Requires=radico8.service

[Service]
Restart=always
EnvironmentFile=/etc/radico8/icecast.env
ExecStart=${TARGET_DIR}/start_icecast host.docker.internal 8010

[Install]
WantedBy=multi-user.target
EOF

echo "Reloading & restarting systemctl..."
systemctl daemon-reload
systemctl enable  radico8.service radico8-youtube.service radico8-icecast.service
systemctl restart radico8.service radico8-youtube.service radico8-icecast.service
