#!/bin/bash
if [[ "$#" -ne 3 ]]; then echo 'Usage: start_docker <pico-8-path> <cartridges-path> <playlist-path>'; exit 1; fi

PICO_PATH="$1"  # pico8 binary location
CARTRIDGES="$2" # directory with .p8.png files
PLAYLIST="$3"   # file with nl separated file/track pairs

# container requires a UFW rule like this if you want to send traffic to localhost:
# sudo ufw allow in on docker0 to any port XXXX
docker build . -t radico8
docker run -it --label name=radico8 --add-host=host.docker.internal:host-gateway \
    --mount type=bind,readonly,source="$PICO_PATH",target=/opt/pico8 \
    --mount type=bind,readonly,source="$CARTRIDGES",target=/cartridges \
    --mount type=bind,readonly,source="$PLAYLIST",target=/playlist.txt \
    radico8
