#!/bin/bash
CONTAINER=$(docker ps --filter "label=radico8" | tail -n +2 | awk '{print $1}' | head -n 1)
if [[ "$#" -ne 2 ]] || [[ -z "$PASS" ]] || [[ -z "$CONTAINER" ]]; then echo -e 'Usage: PASS=<ICECAST-SOURCE-PASS> '$(basename "$0")' <host> <port>'; exit 1; fi
docker exec -i -e PASS="$PASS" "$CONTAINER" stream_to_icecast "$1" "$2"
