#!/bin/bash
if [[ "$#" -ne 3 ]]; then echo 'Usage: '$(basename "$0")' <pico-8-path> <cartridges-path> <playlist-path>'; exit 1; fi

PICO_PATH="$1"  # pico8 binary location
CARTRIDGES="$2" # directory with .p8.png files
PLAYLIST="$3"   # file with nl separated file/track pairs

# container requires a UFW rule like this if you want to send traffic to localhost:
# sudo ufw allow in on docker0 to any port XXXX

echo 'BUILDING DOCKER'
docker build docker -t radico8

echo 'KILLING PREVIOUS CONTAINERS'
LIST=$(docker ps --filter "label=radico8" | tail -n +2 | awk '{print $1}')
[[ -n $LIST ]] && docker kill $LIST

echo 'RUNNING DOCKER'
docker run -d --label radico8 --add-host=host.docker.internal:host-gateway \
    --mount type=bind,readonly,source="$PICO_PATH",target=/opt/pico8 \
    --mount type=bind,readonly,source="$CARTRIDGES",target=/cartridges \
    --mount type=bind,readonly,source="$PLAYLIST",target=/playlist.txt \
    radico8
