#!/bin/bash
if [[ "$#" -ne 2 ]]; then echo 'USAGE: KEY=<YT-STREAM-KEY> stream_to_youtube <video.gif> <audio-stream-url>'; exit 1; fi
if [[ -z "$KEY"  ]]; then echo 'USAGE: KEY=<YT-STREAM-KEY> stream_to_youtube <video.gif> <audio-stream-url>'; exit 1; fi

VIDEO_FILE="$1"
AUDIO_STREAM_URL="$2"

VBR="1500k"
FPS="24"
QUAL="superfast"
YOUTUBE_URL="rtmp://a.rtmp.youtube.com/live2"

# Most of this command came from this source:
# https://www.radioforge.com/how-to-create-a-live-radio-on-youtube/
ffmpeg -re -f lavfi -i "movie=filename=$VIDEO_FILE:loop=0, setpts=N/(FRAME_RATE*TB)" \
    -thread_queue_size 2048 -i "$AUDIO_STREAM_URL" \
    -map 0:v:0 -map 1:a:0 \
    -map_metadata:g 1:g \
    -vcodec libx264 -pix_fmt yuv420p -preset $QUAL -r $FPS -g $(($FPS * 2)) -b:v $VBR \
    -acodec libmp3lame -ar 44100 -threads 6 -qscale:v 3 -b:a 320000 -bufsize 512k \
    -f flv "$YOUTUBE_URL/$KEY"
