#!/bin/bash
# Pulse audio should be started first. Pico8, icecast, and youtube all depend on this.
pulseaudio -D --exit-idle-time=-1 2>/dev/null

radio /cartridges /playlist.txt /radico8-playlist.pipe | grep --line-buffered '' | \
while read -r line; do
    cart=$(awk -F : '{print $1}' <<< "$line")
    track=$(awk -F : '{print $2}' <<< "$line")
    create_image out.gif "/cartridges/$cart.p8.png" "$track"
    echo "PLAYING: #$cart -- $track"
done
