#!/bin/bash
if [[ "$#" -ne 2 ]] || [[ -z "$PASS" ]]; then echo 'USAGE: PASS=<password> '$(basename "$0")' <server> <port>'; exit 1; fi

SERVER="$1"
PORT="$2"
ffmpeg -nostdin -f alsa -i default -f ogg -metadata title='radico8 - a pico8 radio' -metadata author='various pico-8 artists' -content_type audio/ogg icecast://source:"$PASS"@"$SERVER":"$PORT"/stream.ogg
