#!/bin/bash
if [[ "$#" -ne 1 ]] || [[ -z "$PASS" ]]; then echo 'USAGE: PASS=<password> '$(basename "$0")' <url>'; exit 1; fi
URL="$1"

VIDEO_FILE="out.gif"
VBR="1500k"
FPS="24"
QUAL="superfast"

# Most of this command came from this source:
# https://www.radioforge.com/how-to-create-a-live-radio-on-youtube/
ffmpeg -nostdin -re -f lavfi -i "movie=filename=$VIDEO_FILE:loop=0, setpts=N/(FRAME_RATE*TB)" \
    -thread_queue_size 2048 -f alsa -i default \
    -map 0:v:0 -map 1:a:0 \
    -map_metadata:g 1:g \
    -vcodec libx264 -pix_fmt yuv420p -preset $QUAL -r $FPS -g $(($FPS * 2)) -b:v $VBR \
    -acodec libmp3lame -ar 44100 -threads 6 -qscale:v 3 -b:a 320000 -bufsize 512k \
    -f flv "$URL/$PASS"
