#!/bin/bash
if [[ -z "$CHANNEL_NAME" ]]; then
    echo 'USAGE: CHANNEL_NAME=<channel-name> '$(basename "$0")
    exit 1
fi

# Make http request to check if stream is live.
# If live, canonical link tag should be:
# <link rel="canonical" href="https://www.youtube.com/watch?v=your_video_id">
# If not live, canonical link tag should be:
# <link rel="canonical" href="https://www.youtube.com/channel/your_channel_id">
wget -q --output-document - "https://www.youtube.com/@${CHANNEL_NAME}/live" \
	| grep -qEo "<link rel=\"canonical\" href=\"https://www\.youtube\.com/watch\?v="

# Stream is up
if [ $? -eq 0 ]; then
    echo 'stream is up!'
	exit 0
else
    # For testing, just print whether the stream is up first.
    echo 'stream is down!'

    # But really, we'll want to restart something:
    # systemctl restart radico8-youtube.service radico8-youtube-backup.service
    exit 1
fi
