#!/bin/bash
# simple check to see if a youtube livestream is up

if [[ "$#" -ne 1 ]]; then
    echo 'USAGE: '$(basename "$0")' <channel-name>'
    exit 1
fi

# Make http request to check if stream is live.
# If live, canonical link tag should be:
# <link rel="canonical" href="https://www.youtube.com/watch?v=your_video_id">
# If not live, canonical link tag should be:
# <link rel="canonical" href="https://www.youtube.com/channel/your_channel_id">
curl -s "https://www.youtube.com/@${1}/live" \
    | grep -qEo "<link rel=\"canonical\" href=\"https://www\.youtube\.com/watch\?v="

if [ $? -eq 0 ]; then
    echo 'stream is up!'
    exit 0
else
    echo 'stream is down!'
    exit 1
fi
