#!/bin/bash
if [[ "$#" -ne 2 ]]; then echo 'USAGE: '$(basename "$0")' <playlist-path> <cart-dir-path>'; exit 1; fi

PLAYLIST_PATH="$1"
CARTS_PATH="$2"

sanitize() {
    sed -E 's/#.*$|\s//g' | grep -vE '^:|^$' | sort -uV
}

PLAYLIST=$(curl -s https://raw.githubusercontent.com/alanxoc3/radico8/main/playlist.txt | sanitize)

# found the pico8 api thanks to https://www.ebartsoft.com/pico8
for cart in $(echo "$PLAYLIST" | awk -F : '{print $1}' | sort -u); do
    fullcartpath="$CARTS_PATH/$cart.p8.png"
    if [[ ! -f "$fullcartpath" ]] || [[ ! -s "$fullcartpath" ]]; then
        url="https://www.lexaloffle.com/bbs/get_cart.php?cat=7&play_src=2&lid=$cart"
        echo "CART DOWNLOAD: $url"
        wget "$url" -O "$fullcartpath"

        echo "SLEEP zzz"  # be polite to the server!
        sleep 5.00  # 3s is still too frequent -- many ERROR 429
    fi

    infocartpath="$CARTS_PATH/$cart.txt"
    if [[ ! -f "$infocartpath" ]] || [[ ! -s "$infocartpath" ]]; then
        url="https://www.lexaloffle.com/bbs/cpost_lister3.php?lid=$cart"
        echo "TEXT DOWNLOAD: $url"
        wget "$url" -O "$infocartpath"
    fi
done

# Save after wget, to ensure the file actually exists.
echo Saved size: $(echo "$PLAYLIST" | tee "$PLAYLIST_PATH" | wc)
