#!/bin/bash
# Pico8 radio local play.
# Uses the playlist.txt file to find carts in the cartridge directory.
# Requires standard linux cli tools: bash, sed, grep, sort, tail, cat, shuf, mkfifo, mkdir
# Will create one file if it doesn't exist: ~/.cache/radico8.fifo

# Pico8 might generate some ALSA error messages we need to ignore.
if [[ "$#" -ne 3 ]]; then echo 'USAGE: '$(basename "$0")' <pico8-exec-path> <cartridge-dir> <playlist-file>'; exit 1; fi

sanitize() {
    sed -E 's/#.*$|\s//g' | grep -vE '^:|^$' | sort -uV
}

PICO8_EXECUTABLE=$1
CART_DIR=$2
PLAYLIST=$3
FIFO="$HOME/.cache/radico8.fifo"

# first, create the fifo if it doesn't already exist.
[ ! -p "$FIFO" ] && mkdir -p "$HOME/.cache" && mkfifo "$FIFO"

# now start the radio. requires a "radico8.p8" file in the cartridges directory.
# the way this works is:
# - the playlist is shuffled and sent to the fifo
# - pico8 reads from the fifo (stdin)
# - when all songs in the playlist have been played, check the playlist file for any changes and go back to step 1.
tail -f "$FIFO" | grep --line-buffered '' | \
SDL_VIDEODRIVER=dummy $PICO8_EXECUTABLE -accept_future 1 -root_path "$CART_DIR" -run "$CART_DIR/radico8" | \
grep --line-buffered '' | \
while read -r line; do
    if [[ "$line" = "###" ]]; then
        cat "$PLAYLIST" | sanitize | shuf > "$FIFO"
        echo "###" > "$FIFO" # triggers pico8 script that we are done here
    else
        echo "$line"
    fi
done
