#!/bin/bash
if [[ "$#" -ne 4 ]]; then echo 'Usage: '$(basename "$0")' <docker-build-dir> <pico-8-path> <cartridges-path> <playlist-path>'; exit 1; fi

DOCKER_DIR="$1" # directory to dockerfile
PICO_PATH="$2"  # pico8 binary location absolute
CARTRIDGES="$3" # directory with .p8.png files absolute
PLAYLIST="$4"   # file with nl separated file/track pairs absolute

# container requires a UFW rule like this if you want to send traffic to localhost:
# sudo ufw allow in on docker0 to any port XXXX

echo 'BUILDING DOCKER'
docker build "$DOCKER_DIR" -f radico8.docker -t radico8

echo 'KILLING PREVIOUS CONTAINER'
docker kill radico8 2>/dev/null
docker rm   radico8 2>/dev/null

echo 'RUNNING DOCKER'
docker run -i --rm --name radico8 --add-host=host.docker.internal:host-gateway \
    --mount type=bind,readonly,source="$PICO_PATH",target=/opt/pico8 \
    --mount type=bind,readonly,source="$CARTRIDGES",target=/cartridges \
    --mount type=bind,readonly,source="$PLAYLIST",target=/playlist.txt \
    radico8

# this might give you audio for debugging: --device /dev/snd
